#!/usr/bin/env python3
"""Write local-config.js — untracked local dev overrides for the game.

The Google Photorealistic 3D Tiles ground (Pebble) is gated on a Map Tiles API
key. That key is billed per session, so it must never land in a tracked file:
one `git commit -a` from a parallel agent would push it to a public repo.
So it lives in local-config.js, which is gitignored, and index.html loads it on
localhost/.local only.

Reads the key from web/.env.local (VITE_GOOGLE_MAPS_API_KEY) unless --key is
given. Also grants a local dev entitlement for the gtiles courses so they are
playable without first having to hole out an ace.

    python3 tools/local_config.py              # key from web/.env.local
    python3 tools/local_config.py --key AIza…  # explicit
    python3 tools/local_config.py --no-unlock  # key only, respect course locks
"""

import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ENV = ROOT / "web" / ".env.local"
OUT = ROOT / "local-config.js"

# Courses whose ground is Google photoreal tiles (GTILES_IDS in game.js).
GTILES_COURSES = ["pebble-beach-golf-course"]


def key_from_env() -> str:
    if not ENV.exists():
        sys.exit(f"no {ENV.relative_to(ROOT)} — pass --key instead")
    m = re.search(r"^VITE_GOOGLE_MAPS_API_KEY=(\S+)", ENV.read_text(), re.M)
    if not m:
        sys.exit(f"VITE_GOOGLE_MAPS_API_KEY not set in {ENV.relative_to(ROOT)}")
    return m.group(1)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--key", help="Map Tiles API key (default: from web/.env.local)")
    ap.add_argument("--no-unlock", action="store_true",
                    help="skip the dev course entitlement")
    args = ap.parse_args()

    key = args.key or key_from_env()
    unlock = "" if args.no_unlock else f"""
  // Dev entitlement so the photoreal courses are playable without the
  // achievement gate. Same bucket purchases/bookings write to, so the Trophy
  // Room stays honest — no fake milestone is granted. Delete
  // localStorage "golf.entitlements" to undo.
  try {{
    var K = "golf.entitlements";
    var e = JSON.parse(localStorage.getItem(K) || '{{"v":1,"courses":{{}}}}');
    e.courses = e.courses || {{}};
    {json.dumps(GTILES_COURSES)}.forEach(function (id) {{
      if (!e.courses[id]) e.courses[id] = {{ via: "dev", at: new Date().toISOString() }};
    }});
    localStorage.setItem(K, JSON.stringify(e));
  }} catch (err) {{}}
"""

    OUT.write_text(f"""// GENERATED by tools/local_config.py — GITIGNORED, do not commit.
// Local dev overrides, loaded by index.html on localhost/.local only.
(function () {{
  // Map Tiles API key for the Google photoreal ground. Billed per session.
  window.GOOGLE_TILES_TOKEN = {json.dumps(key)};
  try {{ localStorage.setItem("golf.googleTilesToken", window.GOOGLE_TILES_TOKEN); }} catch (err) {{}}
{unlock}}})();
""")
    print(f"wrote {OUT.relative_to(ROOT)}  (key {key[:4]}…{len(key)} chars"
          f"{'' if args.no_unlock else f', unlocked {len(GTILES_COURSES)} course(s)'})")
    print("reload http://localhost:8080/ — Pebble now renders on Google tiles")


if __name__ == "__main__":
    main()
